export type Medication = {
    Nom: string;
    Dosage: string;
    Forme: number;
    Unit: string;
    DCI: string;
    Classe: string;
    SousClasse: string;
    Laboratoire: string;
    AMM: string;
    DateAMM: string;
    Conditionnementprimaire: string;
    Duréeconservation: number;
    Indications: string;
    StockDisponible: number;
    StockMoyen: number;
    StockMin:number;
    StockAlerte: number;
    StockSécurité: number;
    StockMax: number; 
    [key: string]: any;
    'Stock dispo': number;
  };